/*---------------------------------------------------------------------------

    (c) 2004 Scorpio Software
        19 Wittama Drive
        Glenmore Park
        Sydney NSW 2745
        Australia

-----------------------------------------------------------------------------

    $Workfile::                                                           $
    $Revision::                                                           $
        $Date::                                                           $
      $Author::                                                           $

---------------------------------------------------------------------------*/
//---------------------------------------------------------------------------
#ifndef ImageParserPluginH
#define ImageParserPluginH
//---------------------------------------------------------------------------
#include "ZXBasePlugin.h"
//---------------------------------------------------------------------------
using namespace Scorpio;
using namespace Plugin;
//using namespace CodeEditor;
//---------------------------------------------------------------------------
// Plugin Class
/**
 * @class   ImageParser class
 * @brief   This class was generated by the KiwiWare Plugin Wizard.
 * @brief   It is the basis for constructing a KiwiWare compatible plugin.
 * @author  KiwiWare Plugin Wizard
 * @date    Created 17 December 2001 by Tony Thompson
 * @remarks Copyright Scorpio Software 2001
 */
//---------------------------------------------------------------------------
class ZXImageParserPlugin : public ZXBasePlugin
{
public:
                    __fastcall  ZXImageParserPlugin();
                    __fastcall ~ZXImageParserPlugin();

            HRESULT __fastcall  InitialisePlugin    (ZXPlugin* pPlugin);
            HRESULT __fastcall  ReleasePlugin       (void);
            void    __fastcall  RegisterEvents      (void);

            HRESULT __fastcall  GetOptionsPanel(TPanel*& Panel);
            HRESULT __fastcall  GetResourceTypes(KXmlInfo*& XmlData, TStringList*& Types);
            HRESULT __fastcall  GetResourcesList(KXmlInfo*& XmlData, const String& sType, TStringList*& Resources);
            HRESULT __fastcall  ParseResources(KXmlInfo*& XmlData, String& Resource, TStringList*& Code);

    // Events
    //static  HRESULT WINAPI      EventSaveQuery      (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
};
//---------------------------------------------------------------------------
ZXImageParserPlugin* NewPluginClass(void);
//---------------------------------------------------------------------------
#endif
