/*---------------------------------------------------------------------------

    (c) 2004 Scorpio Software
        19 Wittama Drive
        Glenmore Park
        Sydney NSW 2745
        Australia

-----------------------------------------------------------------------------

    $Workfile::                                                           $
    $Revision::                                                           $
        $Date::                                                           $
      $Author::                                                           $

---------------------------------------------------------------------------*/
//---------------------------------------------------------------------------
#ifndef StringTableParserPluginH
#define StringTableParserPluginH
//---------------------------------------------------------------------------
#include <map>
#include "ZXBasePlugin.h"
//---------------------------------------------------------------------------
using namespace Scorpio;
using namespace Plugin;
//using namespace CodeEditor;
//---------------------------------------------------------------------------
// Plugin Class
/**
 * @class   StringTableParser class
 * @brief   This class was generated by the KiwiWare Plugin Wizard.
 * @brief   It is the basis for constructing a KiwiWare compatible plugin.
 * @author  KiwiWare Plugin Wizard
 * @date    Created 17 December 2001 by Tony Thompson
 * @remarks Copyright Scorpio Software 2001
 */
//---------------------------------------------------------------------------
class StringTableParserPlugin : public ZXBasePlugin
{
private:
    void        __fastcall  BuildTilesStringTable(KXmlInfo*& XmlData);
    HRESULT     __fastcall  ParseMasterTable(KXmlInfo*& XmlData, TStringList*& Code, const String& sName);
    HRESULT     __fastcall  ParseStringTable(KXmlInfo*& XmlData, TStringList*& Code);
    void        __fastcall  GetResourceInfo(const String& sResource, String& sType, String& sName);
    String      __fastcall  NumToStr(unsigned char iNum, char cPrefix = ' ');


public:
                __fastcall  StringTableParserPlugin();
                __fastcall ~StringTableParserPlugin();

    HRESULT     __fastcall  InitialisePlugin    (ZXPlugin* pPlugin);
    HRESULT     __fastcall  ReleasePlugin       (void);
    void        __fastcall  RegisterEvents      (void);

    HRESULT     __fastcall  GetOptionsPanel(TPanel*& Panel);
    HRESULT     __fastcall  GetResourceTypes(KXmlInfo*& XmlData, TStringList*& Types);
    HRESULT     __fastcall  GetResourcesList(KXmlInfo*& XmlData, const String& sType, TStringList*& Resources);
    HRESULT     __fastcall  ParseResources(KXmlInfo*& XmlData, String& Resource, TStringList*& Code, String& ParserData);

    // Events
    //static  HRESULT WINAPI      EventSaveQuery      (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
};
//---------------------------------------------------------------------------
StringTableParserPlugin* NewPluginClass(void);
//---------------------------------------------------------------------------
#endif
