/*---------------------------------------------------------------------------

    (c) 2004 Scorpio Software
        19 Wittama Drive
        Glenmore Park
        Sydney NSW 2745
        Australia

-----------------------------------------------------------------------------

    $Workfile::                                                           $
    $Revision::                                                           $
        $Date::                                                           $
      $Author::                                                           $

---------------------------------------------------------------------------*/
//---------------------------------------------------------------------------
#ifndef ZXMapEditorH
#define ZXMapEditorH
//-- APP --------------------------------------------------------------------
#include "TZXMapEditor.h"
#include "TZXTileBrowser.h"
#include "ZXTileManager.h"
#include "fMapEditor.h"
#include "ZXBasePlugin.h"
//---------------------------------------------------------------------------
using namespace Scorpio;
using namespace Plugin;
//---------------------------------------------------------------------------
// Plugin Class
/**
 * @class   ZXMapEditor class
 * @brief   This class was generated by the KiwiWare Plugin Wizard.
 * @brief   It is the basis for constructing a KiwiWare compatible plugin.
 * @author  KiwiWare Plugin Wizard
 * @date    Created 17 December 2001 by Tony Thompson
 * @remarks Copyright KiwiWare 2001
 */
//---------------------------------------------------------------------------
class ZXMapEditor : public ZXBasePlugin
{
private:

public:
                    __fastcall  ZXMapEditor();
                    __fastcall ~ZXMapEditor();

            HRESULT __fastcall  InitialisePlugin    (ZXPlugin* pPlugin);
            HRESULT __fastcall  ReleasePlugin       (void);
            void    __fastcall  RegisterEvents      (void);

    // Events
    static  HRESULT WINAPI      EventSaveQuery      (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventEditQuery      (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventXmlNew         (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventXmlPostLoad    (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventXmlPreSave     (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventXmlUpdate      (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventXmlUndoRestore (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventImageChanged   (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventImageRenamed   (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventEditCopy       (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventEditCut        (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventEditPaste      (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventDelete         (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
    static  HRESULT WINAPI      EventKeyPanel       (ZXEventManager* EventManager, LPDATA lpData, DWORD dwParam, DWORD dwArg);
};
//---------------------------------------------------------------------------
ZXBasePlugin* NewPluginClass(void);
//---------------------------------------------------------------------------
#endif//ZXMapEditor
