;------------------------------------------------------------------------------;
;  Memory.asm                                                                  ;
;  Contains definitions for common ZX Spectrum addresses                       ;
;------------------------------------------------------------------------------;

SCREEN      equ 16384
SCRLEN      equ 6144
ATTRS       equ 22528
ATTRLEN     equ 768