;****************************************************************************
;                      WARNING: DO NOT EDIT THIS SECTION!                    
;      This section gets automatically generated by the Resource Editor      
;   And any data here will get overwritten, when the resources are updated   
;****************************************************************************
; [RESOURCES SECTION                                                         
; [RESOURCE: <Parser:Attribute Based Images><Resource:Sprite\BlueGuy><Data:ScanlinesRowColumn:PlaceSize:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : BlueGuy
; Size   : 16x16
; Palette: ZX Spectrum Hi Colour
; Masked : No
; RowOrder: Classic
BlueGuy:
defb 2, 2             ; size: WxH - (chars x chars)
; pixels and mask bit pairs
defb  63, 254
defb 127, 137
defb 255, 118
defb 254, 255
defb 254, 237
defb 254, 237
defb 222, 255
defb 159, 118
defb 191, 137
defb 223, 255
defb 127, 190
defb  63, 193
defb  15, 255
defb   7, 188
defb   7,  28
defb  10, 170
; attrs
defb  69,  69
defb  69,  69
defb  69,   5
defb  69,   5
defb  69,  79
defb  69,  79
defb  69,  15
defb  69,   7
defb  69,  69
defb  69,  69
defb   5,   5
defb   5,   5
defb   5,   5
defb   5,   5
defb   4,   4
defb   4,   4
; ]RESOURCE: <Parser:Attribute Based Images><Resource:Sprite\BlueGuy>]        

; [RESOURCE: <Parser:Attribute Based Images><Resource:Sprite\RedBuy><Data:ScanlinesRowColumn:PlaceSize:XChar:YChar:MaskBeforePixels:MaskInvert:UseAttributes>]
; Name   : RedBuy
; Size   : 16x16
; Palette: ZX Spectrum Hi Colour
; Masked : No
; RowOrder: Classic
RedBuy:
defb 2, 2             ; size: WxH - (chars x chars)
; pixels and mask bit pairs
defb   3, 142
defb   6, 219
defb   6, 219
defb   3, 142
defb   3, 142
defb  97, 140
defb 209, 140
defb 193, 140
defb 193, 140
defb 227, 222
defb 247, 255
defb 255, 255
defb 255, 219
defb 251,   0
defb 125, 254
defb  63, 252
; attrs
defb  71,  71
defb  71,  71
defb   7,   7
defb   7,   7
defb   3,  67
defb   3,  67
defb   2,  66
defb   2,  66
defb   3,  67
defb   3,  67
defb  66,  66
defb  66,  66
defb  67,  70
defb  67,   0
defb   2,   2
defb   2,   2
; ]RESOURCE: <Parser:Attribute Based Images><Resource:Sprite\RedBuy>]         

; ]RESOURCE: <Parser:Attribute Based Images><Resource:Sprite>]                

; ]RESOURCES SECTION                                                         
