/*---------------------------------------------------------------------------

    (c) 2004 Scorpio Software
        19 Wittama Drive
        Glenmore Park
        Sydney NSW 2745
        Australia

-----------------------------------------------------------------------------

    $Workfile::                                                           $
    $Revision::                                                           $
        $Date::                                                           $
      $Author::                                                           $

---------------------------------------------------------------------------*/
//---------------------------------------------------------------------------
#ifndef ImageEditorH
#define ImageEditorH
//-- APP --------------------------------------------------------------------
#include "..\ZXImage.h"
#include "ZXBasePlugin.h"
//---------------------------------------------------------------------------
using namespace Scorpio;
using namespace Plugin;
//---------------------------------------------------------------------------
// Plugin Class
/**
 * @class   ZXScreenType class
 * @brief   This class was generated by the KiwiWare Plugin Wizard.
 * @brief   It is the basis for constructing a KiwiWare compatible plugin.
 * @author  KiwiWare Plugin Wizard
 * @date    Created 17 December 2001 by Tony Thompson
 * @remarks Copyright Scorpio Software 2001
 */
//---------------------------------------------------------------------------
class ZXScreenType : public ZXBasePlugin
{
public:
                    __fastcall  ZXScreenType();
                    __fastcall ~ZXScreenType();

            HRESULT __fastcall  InitialisePlugin    (ZXPlugin* pPlugin);
            HRESULT __fastcall  ReleasePlugin       (void);
            void    __fastcall  RegisterEvents      (void);

    // Events
    static  HRESULT WINAPI      EventImageChanged   (ZXEventManager* EventManager, LPDATA lpData, DWORD Param, DWORD Arg);
    static  HRESULT WINAPI      EventImageListRefresh(ZXEventManager* EventManager,LPDATA lpData, DWORD Param, DWORD Arg);
    static  HRESULT WINAPI      EventXmlPostLoad    (ZXEventManager* EventManager, LPDATA lpData, DWORD Param, DWORD Arg);
    static  HRESULT WINAPI      EventXmlPreSave     (ZXEventManager* EventManager, LPDATA lpData, DWORD Param, DWORD Arg);
};
//---------------------------------------------------------------------------
ZXScreenType* NewPluginClass(void);
//---------------------------------------------------------------------------
#endif
